QuizApp/Entities/Answer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace QuizApp.Entities
{
    public class Answer
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [DisplayName("Answer")]
        public string Text { get; set; }
    }
}

QuizApp/Entities/Question.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace QuizApp.Entities
{
    public class Question
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [DisplayName("Question")]
        public string Text { get; set; }

        public int CorrectAnswerId { get; set; }

        public virtual ICollection<Answer> Answers { get; set; }
    }
}

QuizApp/Models/QuestionModelView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using QuizApp.Entities;

namespace QuizApp.Models
{
    public class QuestionModelView
    {
        public Question Question { get; set; }

        public List<Answer> Answers { get; set; }

    }
}

QuizApp/Controllers/AnswersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuizApp.Entities;
using QuizApp.Models;
using QuizApp.Repositories.Abstract;
using QuizApp.Services.Abstract;

namespace QuizApp.Controllers
{
    public class AnswersController : Controller
    {
        private readonly IAnswerRepository _repository;
        private readonly IAnswerService _answerService;

        public AnswersController(IAnswerRepository repository, IAnswerService answerService)
        {
            _repository = repository;
            _answerService = answerService;
        }

        // GET: Answers
        public ActionResult Index()
        {
            var answers = _repository.GetAll();
            return View(answers);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Answer answer)
        {
            if (ModelState.IsValid)
            {
                _repository.Insert(answer);
                return RedirectToAction("Index");
            }

            return View(answer);
        }

        public ActionResult Edit(int id)
        {
            Answer answer = _repository.Get(id);

            if (answer == null)
            {
                return HttpNotFound("Answer with specified id does not exist.");
            }

            return View(answer);
        }

        [HttpPost]
        public ActionResult Edit(Answer answer)
        {
            if (ModelState.IsValid)
            {
                _repository.Edit(answer);
                return RedirectToAction("Index");
            }

            return View(answer);
        }

        public ActionResult Delete(int id)
        {
            Answer answer = _repository.Get(id);

            if (answer != null)
            {
                _repository.Remove(id);
                return RedirectToAction("Index");
            }

            return HttpNotFound("Answer with specified id does not exist.");
        }

        public ActionResult CreateAnswers()
        {
            List<Answer> answers = new List<Answer>(4)
            {
                new Answer(),
                new Answer(),
                new Answer(),
                new Answer()
            };
            QuestionModelView model = new QuestionModelView {Answers = answers, Question = new Question()};
            ViewBag.AnswersSelectList = _answerService.GetAnswersSelectList();
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateAnswers(QuestionModelView modelView)
        {

            return View(modelView);
        }
    }
}

QuizApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuizApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

QuizApp/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuizApp.Entities;
using QuizApp.Models;
using QuizApp.Repositories.Abstract;
using QuizApp.Services.Abstract;

namespace QuizApp.Controllers
{
    public class QuestionsController : Controller
    {
        private readonly IQuestionRepository _questionRepository;
        private readonly IAnswerRepository _answerRepository;
        private readonly IAnswerService _answerService;

        public QuestionsController(IQuestionRepository questionRepository, IAnswerRepository answerRepository, IAnswerService answerService)
        {
            _questionRepository = questionRepository;
            _answerRepository = answerRepository;
            _answerService = answerService;
        }

        // GET: Questions
        public ActionResult Index()
        {
            var data = _questionRepository.GetAll();
            return View(data);
        }

        public ActionResult Create()
        {
            ViewBag.AnswersSelectList = _answerService.GetAnswersSelectList();
            QuestionModelView modelView = new QuestionModelView
            {
                Answers = new List<Answer>(4) {new Answer(), new Answer(), new Answer(), new Answer()},
                Question = new Question()
            };

            return View(modelView);
        }

        [HttpPost]
        public ActionResult Create(QuestionModelView modelView)
        {
            ViewBag.AnswersSelectList = _answerService.GetAnswersSelectList();

            modelView.Question.Answers = modelView.Answers;
            modelView.Question.CorrectAnswerId = modelView.Answers[0].Id;

            if (ModelState.IsValid)
            {
                Question question = new Question();

                question.Text = modelView.Question.Text;
                question.Answers = modelView.Answers;

                int index = -1;
                for (int i = 0; i < question.Answers.Count; i++)
                {
                    Answer answer = question.Answers.ElementAt(i);
                    if (i == 0)
                    {
                        index = _answerRepository.Insert(question.Answers.ElementAt(i));
                    }
                    else
                        _answerRepository.Insert(answer);
                }

                question.CorrectAnswerId = index;

                _questionRepository.Insert(question);

                return RedirectToAction("Index");
            }

            return View(modelView);
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            if (_questionRepository.Get(id) != null)
            {
                _questionRepository.Remove(id);
                return RedirectToAction("Index");
            }

            return HttpNotFound("Question with specified id does not exist!");
        }
    }
}

QuizApp/Views/Answers/Create.cshtml
@model QuizApp.Entities.Answer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Answer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QuizApp/Views/Answers/CreateAnswers.cshtml
@using QuizApp.Entities
@model QuizApp.Models.QuestionModelView

@{
    ViewBag.Title = "CreateAnswers";
}

<h2>CreateAnswers</h2>

@using (Html.BeginForm())
{

<div class="form-horizontal">
    @for (int i = 0; i < Model.Answers.Count; i++)
    {
        <div class="form-group">
            @Html.LabelFor(model => model.Answers[i].Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answers[i].Text, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
    }

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="CreateAnswers" class="btn btn-default" />
        </div>
    </div>
</div>
}

QuizApp/Views/Answers/Edit.cshtml
@model QuizApp.Entities.Answer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Answer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QuizApp/Views/Answers/Index.cshtml
@model IEnumerable<QuizApp.Entities.Answer>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Text)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

QuizApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

QuizApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

QuizApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

QuizApp/Views/Questions/Create.cshtml
@model QuizApp.Models.QuestionModelView

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Question</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Question.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Question.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Question.Text, "", new { @class = "text-danger" })
            </div>
        </div>
        
        @for (int i = 0; i < Model.Answers.Count; i++)
        {
        <div class="form-group">
            @if (i == 0)
            {
                @Html.LabelFor(model => model.Answers[i].Text, "Correct answer", htmlAttributes: new { @class = "control-label col-md-2" })
            }
            else
            {
                @Html.LabelFor(model => model.Answers[i].Text, htmlAttributes: new { @class = "control-label col-md-2" })
            }
            <div class="col-md-10">
                @Html.EditorFor(model => model.Answers[i].Text, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QuizApp/Views/Questions/Index.cshtml
@model IEnumerable<QuizApp.Entities.Question>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Answers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CorrectAnswerId)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Text)
            </td>
            <td>
                <ol>
                    @foreach (var a in item.Answers)
                    {
                        <li>@a.Text</li>
                    }
                </ol>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CorrectAnswerId)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }

</table>

QuizApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Manage Questions", "Index", "Questions")</li>
                    <li>@Html.ActionLink("Manage answers", "Index", "Answers")</li>
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>